Class: CS-4200 
Assignment: Project-1 (K-Nearest Neighbor)
Author: Nick House
Date: 11/16/2020
Description: Demonstrate use of Numpy by implementing a K-NN algorithm

In [1]:
import numpy as np

class KNN:    
    
    X_test = X_train = Y_test = Y_train = ogArray = ogLabel = np.array
    distances = neighbor = []
    GBU = ['Good', 'Bad', 'Ugly']
    
    # n = size of training set, TOTAL_SAMPLE_SIZE, d = features,K = # of Neighbors, m = mean, s = Standard Deviation, Seed 
    def __init__(self, n, TOTAL_SAMPLE_SIZE, d, K, m, s, Seed):
        self.n = n
        self.TOTAL_SAMPLE_SIZE = TOTAL_SAMPLE_SIZE
        self.d = d
        self.K = K
        self.m = m
        self.s = s
        self.testNum = TOTAL_SAMPLE_SIZE - n
        self.Seed = Seed
        self.setSeed(Seed)
        self.createRandom()
        self.createLabels()
        self.TrainTestSplit()
        
    #Randomly generate 
    def createRandom(self):
        self.ogArray = np.random.normal(loc=self.m, scale=self.s, size=(self.TOTAL_SAMPLE_SIZE, self.d))
    
    #Create numpy array of GOOD BAD UGLY
    def createLabels(self):
        self.ogLabel = np.random.choice(["Good", "Bad", "Ugly"], size = self.TOTAL_SAMPLE_SIZE)
    
    #Set Seed
    def setSeed(self, Seed):
        np.random.seed(Seed)  
        self.Seed = Seed
        
    def getSeed(self):
        return self.Seed
        
    def getX_test(self):
        return self.X_test
    
    def getX_train(self):
        return self.X(train)
    
    def getY_test(self):
        return self.Y_test
    
    def getY_train(self):
        return self.Y_train
    
    def getOGArray(self):
        return self.ogArray
    
    def getOGLabel(self):
        return self.ogLabel
    
    #Print original arrays and Labels
    def printOriginalValues(self):
        
        length = self.TOTAL_SAMPLE_SIZE
        reLabel = self.ogLabel.reshape(length , 1)
        for x in range(length):
            print(self.ogArray[x], end= " : ")
            print(reLabel[x])
            
    #Print Test Set array and Labels       
    def printTestValues(self):
        
        length = self.testNum
        reLabel = self.Y_test.reshape(length , 1)
        for index in range(self.testNum):
            print(self.X_test[index], end= " : ")
            print(reLabel[index])      
            
    #Print Training Set array and Labels       
    def printTrainValues(self):
        
        length = self.n
        reLabel = self.Y_train.reshape(length , 1)
        for index in range(self.n):
            print(self.X_train[index], end= " : ")
            print(reLabel[index]) 
           
    #Print Test Set Array and Labels
    def TrainTestSplit(self):
        
        #Train/Test Split
        np.random.shuffle(self.ogArray)
        np.random.shuffle(self.ogLabel)
        
        #Training Set
        self.X_train, self.Y_train = self.ogArray[:self.n], self.ogLabel[:self.n]
        #Test Set
        self.X_test, self.Y_test = self.ogArray[self.n:,:], self.ogLabel[self.n:]
    
    #Main K_NN function   
    def kNN(self, testIndex):
        
        self.distances.clear()
        self.neighbor.clear()
        
        for index in range(len(self.X_train)):
            weight = self.__distance(self.X_test[testIndex], self.X_train[index])
            self.distances.append((weight, index, self.Y_train[index]))
            self.distances.sort(key=lambda x: x[0], reverse = True) 
            self.neighbor = self.distances[:self.K] 
        
        return self.neighbor

    #Get Distance :: np.linalg.norm(V1 - V2)
    def __distance(self, v1, v2):
        
        v1 = np.array(v1)
        v2 = np.array(v2)
        
        return self.__weight(np.linalg.norm(v1-v2)) 

    #Get Weight
    def __weight(self, distance):
        
        return 1/(.001 + distance)
     
    #Sum Weights of Neibhors GBU and return the max
    def goodBadUgly(self):
        
        good = list(filter(lambda x: x[:][0] == 'Good', self.neighbor))
        bad = list(filter(lambda x: x[:][2] == 'Bad', self.neighbor))
        ugly = list(filter(lambda x: x[:][2] == 'Ugly', self.neighbor))
        
        A = {'Good': sum([val[0] for val in good]), 'Bad': sum([val[0] for val in bad]), 'Ugly': sum([val[0] for val in ugly])}
        
        return max(A, key=lambda k: A[k]) 

        
    def printNeighbor(self):
        
        count = 0; 
        
        for i in range(self.testNum):
            self.kNN(i)
            predict = self.goodBadUgly()
            actual = self.Y_test[i]
            if(predict == actual):
                count = count + 1
            print("Predicted class label: " + str(predict))
            print("Tested (known) label: " + str(actual) +"\n")
        
        print("Accuracy: " + str(count)+ "/" + str(self.testNum))            

In [2]:
# n = 7, TOTAL_SAMPLE_SIZE = 10, d = 3, K = 3, m = 5, s = 2, Seed = 2800
#Create KNN object
knn = KNN( 7, 10, 3, 3, 5, 2, 2800 )

#Print Training Data w/Labels
print("---------------- Training Set ----------------")
knn.printTrainValues()

print("\n---------------- Testing Set ----------------")
knn.printTestValues()
print()

#Print Results
knn.printNeighbor()
print("Seed: " + str(knn.getSeed()))

---------------- Training Set ----------------
[3.9659518  2.86882899 5.08144525] : ['Good']
[7.96695742 3.814357   3.66426287] : ['Good']
[8.01007624 5.85947838 1.12810555] : ['Bad']
[7.39337685 8.19427429 2.40101081] : ['Bad']
[2.58764907 2.18915402 6.99758839] : ['Bad']
[6.42701377 5.28660351 6.64714246] : ['Bad']
[3.14518357 5.2760616  2.31081518] : ['Good']

---------------- Testing Set ----------------
[5.98845188 3.02793238 6.64292022] : ['Bad']
[4.44414624 3.50775637 2.71107878] : ['Good']
[2.98832801 6.00689288 7.39846678] : ['Ugly']

Predicted class label: Bad
Tested (known) label: Bad

Predicted class label: Good
Tested (known) label: Good

Predicted class label: Bad
Tested (known) label: Ugly

Accuracy: 2/3
Seed: 2800


In [3]:
#Create KNN object w/Seed = 2000
knn = KNN( 7, 10, 3, 3, 5, 2, 2000 )

#Print Training Data w/Labels
print("---------------- Training Set ----------------")
knn.printTrainValues()

print("\n---------------- Testing Set ----------------")
knn.printTestValues()
print()

#Print Results
knn.printNeighbor()
print("Seed: " + str(knn.getSeed()))

---------------- Training Set ----------------
[4.04076048 7.41947753 2.84963228] : ['Bad']
[4.66168793 7.20166888 5.16502104] : ['Good']
[5.27447908 3.59757355 3.75843985] : ['Ugly']
[6.61383841 4.41843306 4.55810472] : ['Ugly']
[4.99124883 1.5548835  7.11511283] : ['Good']
[4.70217581 6.16612311 0.48153394] : ['Good']
[8.47347522 8.79582781 0.78645316] : ['Good']

---------------- Testing Set ----------------
[-0.03582562  1.17871976  7.6129107 ] : ['Ugly']
[3.15615392 6.25280905 5.7143534 ] : ['Bad']
[5.84879528 4.06166384 2.98785494] : ['Ugly']

Predicted class label: Ugly
Tested (known) label: Ugly

Predicted class label: Bad
Tested (known) label: Bad

Predicted class label: Ugly
Tested (known) label: Ugly

Accuracy: 3/3
Seed: 2000
